name: Create daily Docker image for Kenon Frontend on develop

on:
  push:
    branches:
      - stp-changes
  pull_request:
    branches: [stp-changes]
  workflow_dispatch:
  schedule:
   - cron: "0 2 * * *"  # todo dia Ã s 02:00

jobs:
  publish-docker-develop-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: stp-changes

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Kenon Frontend Docker image
        run: |
          LABEL=latest
          docker build --no-cache . --tag ghcr.io/stssocialst-stp/kenon-frontend:${LABEL}
          docker push ghcr.io/stssocialst-stp/kenon-frontend:${LABEL}
